### PR TITLE
fix(developer): url

### PR DESCRIPTION
**Pull request by Ethkuil**
Or there will be "404 This page could not be found." error.

### CODE REVIEW

**Comment by Ethkuil** [comment]
It seems to behave differently in [production](https://bilibili-evolved-doc.vercel.app/docs/developer) and [preview](https://bilibili-evolved-ld9fvfrag-foundthewout.vercel.app/docs/developer).

The production version doesn't add the `docs` prefix in URL, but the preview version does(relative to current path `docs/`).

**Comment by FoundTheWOUT** [comment]
> It seems to behave differently in [production](https://bilibili-evolved-doc.vercel.app/docs/developer) and [preview](https://bilibili-evolved-ld9fvfrag-foundthewout.vercel.app/docs/developer).

i could't find what different between production and preview version, maybe you should try to access the website again? I just rebuild the site.

**Comment by Ethkuil** [comment]
current production version:
production_bug

**Comment by Ethkuil** [comment]
Now everything goes well. The key is absolute and relative paths, the absolute path should begin with `/` while the relative not.

Would you mind squeezing the 2 commits and apply it to production version?

**Pull request merged**
